# Generated by Django 2.2.1 on 2019-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190514_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyses',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
