# Generated by Django 2.2.1 on 2019-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20190514_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='permissive',
            field=models.BooleanField(default=False),
        ),
    ]
