# Generated by Django 2.2.1 on 2019-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analyses_permissive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyses',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
