"""empty message

Revision ID: 1c945540a3cd
Revises: 
Create Date: 2018-04-19 15:09:05.648000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c945540a3cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_sm_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('query_sm', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=17), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_sm_all')
    # ### end Alembic commands ###
