"""empty message

Revision ID: 34320d34b6f8
Revises: 6934b3be5e69
Create Date: 2018-06-29 15:10:44.205688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34320d34b6f8'
down_revision = '6934b3be5e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path_input', sa.String(length=500), nullable=True),
    sa.Column('path_output', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slowniki')
    # ### end Alembic commands ###
