"""empty message

Revision ID: 37ad2116233b
Revises: 34320d34b6f8
Create Date: 2018-06-29 16:08:10.054482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ad2116233b'
down_revision = '34320d34b6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dicts', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('dicts', sa.Column('os_timestamp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dicts', 'os_timestamp')
    op.drop_column('dicts', 'last_modified')
    # ### end Alembic commands ###
