"""empty message

Revision ID: 827d26c10b59
Revises: 4db39fae4b9b
Create Date: 2018-07-19 16:45:20.106207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827d26c10b59'
down_revision = '4db39fae4b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abc_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('query_sm_all_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_sm_all_id'], ['query_sm_all.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abc_history')
    # ### end Alembic commands ###
